circuit_to_districts = {
    "first": [
        "District of Maine",
        "District of Massachusetts",
        "District of New Hampshire",
        "District of Puerto Rico",
        "District of Rhode Island",
    ],
    "second": [
        "District of Connecticut",
        "Eastern District of New York",
        "Northern District of New York",
        "Southern District of New York",
        "Western District of New York",
        "District of Vermont",
    ],
    "third": [
        "District of Delaware",
        "District of New Jersey",
        "Eastern District of Pennsylvania",
        "Middle District of Pennsylvania",
        "Western District of Pennsylvania",
        "District of the Virgin Islands",
    ],
    "fourth": [
        "District of Maryland",
        "Eastern District of North Carolina",
        "Middle District of North Carolina",
        "Western District of North Carolina",
        "District of South Carolina",
        "Eastern District of Virginia",
        "Western District of Virginia",
        "Northern District of West Virginia",
        "Southern District of West Virginia",
    ],
    "fifth": [
        "Eastern District of Louisiana",
        "Middle District of Louisiana",
        "Western District of Louisiana",
        "Northern District of Mississippi",
        "Southern District of Mississippi",
        "Eastern District of Texas",
        "Northern District of Texas",
        "Southern District of Texas",
        "Western District of Texas",
    ],
    "sixth": [
        "Eastern District of Kentucky",
        "Western District of Kentucky",
        "Eastern District of Michigan",
        "Western District of Michigan",
        "Northern District of Ohio",
        "Southern District of Ohio",
        "Eastern District of Tennessee",
        "Middle District of Tennessee",
        "Western District of Tennessee",
    ],
    "seventh": [
        "Central District of Illinois",
        "Northern District of Illinois",
        "Southern District of Illinois",
        "Northern District of Indiana",
        "Southern District of Indiana",
        "Eastern District of Wisconsin",
        "Western District of Wisconsin",
    ],
    "eighth": [
        "Eastern District of Arkansas",
        "Western District of Arkansas",
        "Northern District of Iowa",
        "Southern District of Iowa",
        "District of Minnesota",
        "Eastern District of Missouri",
        "Western District of Missouri",
        "District of Nebraska",
        "District of North Dakota",
        "District of South Dakota",
    ],
    "ninth": [
        "District of Alaska",
        "District of Arizona",
        "Central District of California",
        "Eastern District of California",
        "Northern District of California",
        "Southern District of California",
        "District of Hawaii",
        "District of Idaho",
        "District of Montana",
        "District of Nevada",
        "District of Oregon",
        "Eastern District of Washington",
        "Western District of Washington",
        "District of Guam",
        "District of the Northern Mariana Islands",
    ],
    "tenth": [
        "District of Colorado",
        "District of Kansas",
        "District of New Mexico",
        "Northern District of Oklahoma",
        "Eastern District of Oklahoma",
        "Western District of Oklahoma",
        "District of Utah",
        "District of Wyoming",
    ],
    "eleventh": [
        "Middle District of Alabama",
        "Northern District of Alabama",
        "Southern District of Alabama",
        "Middle District of Florida",
        "Northern District of Florida",
        "Southern District of Florida",
        "Middle District of Georgia",
        "Northern District of Georgia",
        "Southern District of Georgia",
    ],
    "district_of_columbia": [
        "District of Columbia"
    ]
}